"""Golden corpus — hand-authored (English, expected IR) pairs, Phase 7
(spec §8.4). Committed fixtures, never regenerated by an LLM — these ARE
the ground truth the compiler is measured against.

Two labelled classes (Phase 7 design lock §8.5 — the LLM's contribution
must be MEASURED, not asserted):

    CANONICAL  — phrasing close enough that a fixed grammar/parser could
                 plausibly handle it too. Included so the corpus reports
                 a baseline, not just "the hard cases."
    PARAPHRASE — natural rephrasings only a language model would map
                 correctly to the same IR. This is where an LLM's actual
                 value shows up as a number.

Each entry also carries `expect` — the verdict `sampark.policy.compiler.validate.validate`
must reach (ACCEPTED / FACT_UNAVAILABLE / REJECTED) — so the corpus
exercises the WHOLE deterministic pipeline, not just IR shape.

The four spec §8.4 example sentences appear here verbatim — two of them
(the chargeback rule, the RTO Shield rule) are the two cases proving
FACT_UNAVAILABLE handling is not hypothetical.
"""

from __future__ import annotations

from dataclasses import dataclass
from typing import Any

CANONICAL = "canonical"
PARAPHRASE = "paraphrase"


@dataclass(frozen=True)
class GoldenCase:
    case_id: str
    kind: str  # CANONICAL | PARAPHRASE
    english: str
    expected_ir: dict[str, Any]
    expect_verdict: str  # "ACCEPTED" | "FACT_UNAVAILABLE" | "REJECTED"


GOLDEN_CASES: tuple[GoldenCase, ...] = (
    # --- spec §8.4's own four example sentences ---
    GoldenCase(
        case_id="spec_no_more_than_twice_24h",
        kind=CANONICAL,
        english="Never contact anyone more than twice in 24 hours.",
        # max_contacts=2 (blocks the 3rd+ contact — "more than twice" is
        # permissive up to 2). REJECTED, correctly: SAMPARK's existing
        # frozen cap (CONTACT_CAP_24H=1, sampark/allocator/constants.py)
        # is already stricter than this merchant policy, so a compiled
        # rule at threshold 2 would never bind — a genuine, worth-reporting
        # finding, not a golden-corpus error: the spec's own example
        # sentence turns out to be redundant against this system's
        # existing regulation.
        expected_ir={
            "rule_id": "spec_no_more_than_twice_24h",
            "family": "contact_frequency_cap",
            "params": {"window": "24h", "max_contacts": 2},
            "source_text": "Never contact anyone more than twice in 24 hours.",
        },
        expect_verdict="REJECTED",
    ),
    GoldenCase(
        case_id="spec_no_voice_before_10am",
        kind=CANONICAL,
        english="No voice calls before 10 AM.",
        expected_ir={
            "rule_id": "spec_no_voice_before_10am",
            "family": "time_of_day_window",
            "params": {"channel": "voice", "forbidden_before": "10:00"},
            "source_text": "No voice calls before 10 AM.",
        },
        expect_verdict="ACCEPTED",
    ),
    GoldenCase(
        case_id="spec_no_discount_after_chargeback",
        kind=CANONICAL,
        english="Never offer a discount to a customer who has raised a chargeback in the last 90 days.",
        expected_ir={
            "rule_id": "spec_no_discount_after_chargeback",
            "family": "incentive_prohibition",
            "condition": {"fact": "chargeback_90d", "op": "exists"},
            "source_text": "Never offer a discount to a customer who has raised a chargeback in the last 90 days.",
        },
        expect_verdict="FACT_UNAVAILABLE",
    ),
    GoldenCase(
        case_id="spec_stop_recovery_on_rto_flag",
        kind=CANONICAL,
        english="Stop all recovery on an order that RTO Shield has flagged.",
        expected_ir={
            "rule_id": "spec_stop_recovery_on_rto_flag",
            "family": "intent_suppression",
            "params": {"intent": "*"},
            "condition": {"fact": "rto_flagged", "op": "exists"},
            "source_text": "Stop all recovery on an order that RTO Shield has flagged.",
        },
        expect_verdict="FACT_UNAVAILABLE",
    ),
    # --- additional canonical phrasings ---
    GoldenCase(
        case_id="no_whatsapp_more_than_once_7d",
        kind=CANONICAL,
        english="Do not send more than one WhatsApp message per customer per week.",
        # max_contacts=1 (blocks the 2nd+ WhatsApp contact in 7d) — 1 < the
        # existing CONTACT_CAP_7D=2, so this genuinely tightens the system
        # default for this channel. ACCEPTED.
        expected_ir={
            "rule_id": "no_whatsapp_more_than_once_7d",
            "family": "contact_frequency_cap",
            "params": {"window": "7d", "max_contacts": 1, "channel": "whatsapp"},
            "source_text": "Do not send more than one WhatsApp message per customer per week.",
        },
        expect_verdict="ACCEPTED",
    ),
    GoldenCase(
        case_id="no_sms_after_9pm",
        kind=CANONICAL,
        english="No SMS after 9 PM.",
        expected_ir={
            "rule_id": "no_sms_after_9pm",
            "family": "time_of_day_window",
            "params": {"channel": "sms", "forbidden_after": "21:00"},
            "source_text": "No SMS after 9 PM.",
        },
        expect_verdict="ACCEPTED",
    ),
    GoldenCase(
        case_id="never_channel_voice",
        kind=CANONICAL,
        english="Never contact customers by voice call for this campaign.",
        expected_ir={
            "rule_id": "never_channel_voice",
            "family": "channel_restriction",
            "params": {"channel": "voice"},
            "source_text": "Never contact customers by voice call for this campaign.",
        },
        expect_verdict="ACCEPTED",
    ),
    # --- paraphrases (only an LLM would map these correctly) ---
    GoldenCase(
        case_id="paraphrase_twice_daily_cap",
        kind=PARAPHRASE,
        english="We don't want our recovery agents reaching out to the same person twice within a single day — once is the limit.",
        # "once is the limit" -> max_contacts=1 (blocks the 2nd+ contact),
        # which EQUALS the existing CONTACT_CAP_24H=1 exactly — redundant
        # (>=, not >), correctly REJECTED: the existing system cap already
        # enforces precisely this.
        expected_ir={
            "rule_id": "paraphrase_twice_daily_cap",
            "family": "contact_frequency_cap",
            "params": {"window": "24h", "max_contacts": 1},
            "source_text": "We don't want our recovery agents reaching out to the same person twice within a single day — once is the limit.",
        },
        expect_verdict="REJECTED",
    ),
    GoldenCase(
        case_id="paraphrase_morning_quiet_voice",
        kind=PARAPHRASE,
        english="Nobody should get a phone call from us before ten in the morning, IST.",
        expected_ir={
            "rule_id": "paraphrase_morning_quiet_voice",
            "family": "time_of_day_window",
            "params": {"channel": "voice", "forbidden_before": "10:00", "tz": "Asia/Kolkata"},
            "source_text": "Nobody should get a phone call from us before ten in the morning, IST.",
        },
        expect_verdict="ACCEPTED",
    ),
    GoldenCase(
        case_id="paraphrase_chargeback_discount_ban",
        kind=PARAPHRASE,
        english="If someone's filed a chargeback with us in the past three months, don't sweeten the deal for them.",
        expected_ir={
            "rule_id": "paraphrase_chargeback_discount_ban",
            "family": "incentive_prohibition",
            "condition": {"fact": "chargeback_90d", "op": "exists"},
            "source_text": "If someone's filed a chargeback with us in the past three months, don't sweeten the deal for them.",
        },
        expect_verdict="FACT_UNAVAILABLE",
    ),
    GoldenCase(
        case_id="paraphrase_mandate_intent_stop",
        kind=PARAPHRASE,
        english="Pause every mandate-retry touchpoint entirely — no exceptions.",
        expected_ir={
            "rule_id": "paraphrase_mandate_intent_stop",
            "family": "intent_suppression",
            "params": {"intent": "mandate_retry"},
            "source_text": "Pause every mandate-retry touchpoint entirely — no exceptions.",
        },
        expect_verdict="ACCEPTED",
    ),
    # --- deliberate rejection cases ---
    GoldenCase(
        case_id="redundant_five_per_day",
        kind=CANONICAL,
        english="Never contact more than 5 times in 24 hours.",
        expected_ir={
            "rule_id": "redundant_five_per_day",
            "family": "contact_frequency_cap",
            "params": {"window": "24h", "max_contacts": 5},
            "source_text": "Never contact more than 5 times in 24 hours.",
        },
        expect_verdict="REJECTED",
    ),
    GoldenCase(
        case_id="out_of_grammar_bad_channel",
        kind=CANONICAL,
        english="Never contact anyone by carrier pigeon.",
        expected_ir={
            "rule_id": "out_of_grammar_bad_channel",
            "family": "channel_restriction",
            "params": {"channel": "carrier_pigeon"},
            "source_text": "Never contact anyone by carrier pigeon.",
        },
        expect_verdict="REJECTED",
    ),
)
