"""Identity resolution — spec §8.2."""

from __future__ import annotations

import pytest

from sampark.identity import (
    ContactSignal,
    canonicalize_email,
    canonicalize_phone,
    email_hash,
    phone_hash,
    resolve_customer_ids,
)


def test_canonicalize_phone_strips_formatting_and_country_code():
    assert canonicalize_phone("+91 98765-43210") == "9876543210"
    assert canonicalize_phone("09876543210") == "9876543210"
    assert canonicalize_phone("9876543210") == "9876543210"


def test_canonicalize_phone_rejects_too_short_input():
    assert canonicalize_phone("12345") is None


def test_canonicalize_email_trims_and_lowercases():
    assert canonicalize_email("  Priya@Example.com ") == "priya@example.com"


def test_canonicalize_email_rejects_blank_input():
    assert canonicalize_email("   ") is None


def test_phone_hash_is_deterministic_and_format_insensitive():
    a = phone_hash("+91 98765 43210")
    b = phone_hash("9876543210")
    assert a == b
    assert a is not None
    assert len(a) == 64  # sha256 hex digest


def test_email_hash_is_deterministic_and_case_insensitive():
    a = email_hash("Priya@Example.com")
    b = email_hash("priya@example.com")
    assert a == b


def test_hash_none_is_none():
    assert phone_hash(None) is None
    assert email_hash(None) is None


def test_two_signals_sharing_a_phone_hash_resolve_to_one_customer():
    signals = [
        ContactSignal("risk-1", phone_hash=phone_hash("9876543210"), email_hash=None),
        ContactSignal("risk-2", phone_hash=phone_hash("+91 98765 43210"), email_hash=None),
    ]
    resolved = resolve_customer_ids(signals)
    assert resolved["risk-1"] == resolved["risk-2"]


def test_signals_with_different_hashes_resolve_to_different_customers():
    signals = [
        ContactSignal("risk-1", phone_hash=phone_hash("9876543210"), email_hash=None),
        ContactSignal("risk-2", phone_hash=phone_hash("9123456780"), email_hash=None),
    ]
    resolved = resolve_customer_ids(signals)
    assert resolved["risk-1"] != resolved["risk-2"]


def test_transitive_link_via_a_third_signal_merges_two_otherwise_unrelated_signals():
    """Signal A has phone only, signal B has email only, signal C (the same
    person, seen through a third channel) has both — proving the resolver
    merges A and B transitively through C rather than requiring a direct
    shared field."""
    shared_phone = phone_hash("9876543210")
    shared_email = email_hash("priya@example.com")

    signals = [
        ContactSignal("risk-a", phone_hash=shared_phone, email_hash=None),
        ContactSignal("risk-b", phone_hash=None, email_hash=shared_email),
        ContactSignal("risk-c", phone_hash=shared_phone, email_hash=shared_email),
    ]
    resolved = resolve_customer_ids(signals)
    assert resolved["risk-a"] == resolved["risk-b"] == resolved["risk-c"]


def test_signal_with_no_hashes_is_its_own_singleton_customer():
    signals = [
        ContactSignal("risk-1", phone_hash=None, email_hash=None),
        ContactSignal("risk-2", phone_hash=None, email_hash=None),
    ]
    resolved = resolve_customer_ids(signals)
    assert resolved["risk-1"] != resolved["risk-2"]


def test_resolution_is_deterministic_across_two_calls():
    signals = [
        ContactSignal("risk-1", phone_hash=phone_hash("9876543210"), email_hash=None),
        ContactSignal("risk-2", phone_hash=phone_hash("9876543210"), email_hash=None),
        ContactSignal("risk-3", phone_hash=phone_hash("9123456780"), email_hash=None),
    ]
    first = resolve_customer_ids(signals)
    second = resolve_customer_ids(list(reversed(signals)))
    assert first["risk-1"] == second["risk-1"]
    assert first["risk-3"] == second["risk-3"]
    assert first["risk-1"] != first["risk-3"]


def test_resolution_is_independent_of_signal_id_labeling():
    """No person_id leakage: relabeling signal_ids (as if generated by a
    different run, or a different ground-truth id scheme entirely) must not
    change which signals get grouped together — only shared hashes may."""
    shared = phone_hash("9876543210")
    signals_a = [
        ContactSignal("alpha", phone_hash=shared, email_hash=None),
        ContactSignal("beta", phone_hash=shared, email_hash=None),
    ]
    signals_b = [
        ContactSignal("zzz-999", phone_hash=shared, email_hash=None),
        ContactSignal("aaa-111", phone_hash=shared, email_hash=None),
    ]
    resolved_a = resolve_customer_ids(signals_a)
    resolved_b = resolve_customer_ids(signals_b)
    assert resolved_a["alpha"] == resolved_a["beta"]
    assert resolved_b["zzz-999"] == resolved_b["aaa-111"]


def test_contact_signal_has_no_person_id_field():
    with pytest.raises(TypeError):
        ContactSignal(  # type: ignore[call-arg]
            signal_id="risk-1",
            phone_hash=None,
            email_hash=None,
            person_id="ground-truth-1",
        )
