"""ModelArtifact — the one committed Phase 6 model artifact.

Mirrors `sampark/allocator/calibrated.py`'s precedent exactly: a
GENERATED FILE (`sampark/models/artifact_data.py`, produced by
`sim/train_phase6_models.py::main()` from Arm A's seed-42 log only,
same as Design Lock §14.1's calibration rule), committed to git, never
hand-edited, and re-derivable byte-for-byte by re-running the training
script.

`build_model_artifact` is deterministic: it calls
`sampark.models.uplift.train_uplift_model` and
`sampark.models.fatigue_hazard.train_fatigue_hazard_model`, both of
which are themselves deterministic given `seed` (no RNG anywhere on
this path), and packages whatever they returned — including an honest
`available=False` — into one `ModelArtifact`.

`ModelArtifact.is_valid_for_scoring()` is deliberately all-or-nothing:
`sampark.models.scorer.ModelBackedScorer` requires BOTH the uplift and
fatigue-hazard components to be available before it will use either.
Scoring half the formula from a fitted model and half from the Phase 4
heuristic would be a third, undocumented scoring regime with no design
sign-off — the Phase 6 contract asks for a clean fallback to the
heuristic, not a silent hybrid.
"""

from __future__ import annotations

from dataclasses import dataclass

from sampark.models.fatigue_hazard import FatigueHazardModel, train_fatigue_hazard_model
from sampark.models.uplift import UpliftModel, train_uplift_model


@dataclass(frozen=True)
class ModelArtifact:
    seed: int
    uplift_available: bool
    uplift_reason: str | None
    uplift_model: UpliftModel | None
    fatigue_hazard_available: bool
    fatigue_hazard_reason: str | None
    fatigue_hazard_model: FatigueHazardModel | None

    def is_valid_for_scoring(self) -> bool:
        """Both components must be available AND actually carry a fitted
        model — an artifact claiming `available=True` with `model=None`
        (which no code path in this repository produces, but which a
        hand-edited or corrupted artifact file could) is treated as
        invalid, not trusted."""
        return (
            self.uplift_available
            and self.uplift_model is not None
            and self.fatigue_hazard_available
            and self.fatigue_hazard_model is not None
        )


def build_model_artifact(seed: int) -> ModelArtifact:
    uplift_result = train_uplift_model(seed)
    fatigue_result = train_fatigue_hazard_model(seed)
    return ModelArtifact(
        seed=seed,
        uplift_available=uplift_result.available,
        uplift_reason=uplift_result.reason,
        uplift_model=uplift_result.model,
        fatigue_hazard_available=fatigue_result.available,
        fatigue_hazard_reason=fatigue_result.reason,
        fatigue_hazard_model=fatigue_result.model,
    )


class CommittedArtifactUnavailableError(RuntimeError):
    """The generated `sampark.models.artifact_data` module is missing,
    unimportable, or missing an expected field. Raised by
    `load_committed_artifact`, caught by
    `sampark.models.scorer.build_scorer`, and treated as "no model" --
    never as a reason to fall back to `build_model_artifact(seed)`
    computed fresh at scoring time, which would make scoring
    non-deterministic across a run (a freshly-trained artifact could
    differ from what was actually committed and reviewed)."""


def load_committed_artifact(module_name: str = "sampark.models.artifact_data") -> ModelArtifact:
    """Loads the COMMITTED artifact (`sampark/models/artifact_data.py` by
    default, generated by `sim/train_phase6_models.py`) -- never
    retrains. This is the one function `sampark.models.scorer.build_scorer`
    calls; it deliberately does not fall back to computing a fresh
    artifact on import failure, because "the model that was reviewed and
    committed" and "whatever training happens to produce right now" must
    never be silently the same code path.

    `module_name` (Phase 7, additive — every pre-Phase-7 caller omits it
    and gets the exact Phase 6 default): the Phase 7 evidence path passes
    `"sampark.models.artifact_data_phase7"` (generated by
    `sim/train_phase7_models.py`), a SEPARATE committed file. Phase 6's
    `sampark/models/artifact_data.py` is never overwritten by Phase 7 —
    if it were, `phase6_model`'s committed results
    (`results/arm_b_phase6_model_metrics_*.json`) would no longer be
    reproducible by re-running that ablation, breaking the regression
    proof "phase6_heuristic/phase6_model bit-for-bit reproduce the Phase
    4 headline" the moment a Phase 7 model became available."""
    import importlib

    try:
        # importlib.import_module (rather than `from sampark.models import
        # artifact_data`) is used deliberately: it always re-checks
        # sys.modules for THIS exact dotted name, so
        # `sys.modules["sampark.models.artifact_data"] = None` (the
        # standard way to simulate "cannot be imported" in a test)
        # reliably raises ImportError here even if some earlier import
        # already bound `artifact_data` as an attribute of the
        # `sampark.models` package object.
        artifact_data = importlib.import_module(module_name)
    except ImportError as exc:
        raise CommittedArtifactUnavailableError(
            f"{module_name} does not exist -- run "
            "`python -m sim.train_phase6_models` (or train_phase7_models) and commit the result first"
        ) from exc

    try:
        uplift_model = (
            UpliftModel(
                treated_response_by_bucket=dict(artifact_data.UPLIFT_TREATED_RESPONSE_BY_BUCKET),
                control_response_by_bucket=dict(artifact_data.UPLIFT_CONTROL_RESPONSE_BY_BUCKET),
            )
            if artifact_data.UPLIFT_AVAILABLE
            else None
        )
        fatigue_hazard_model = (
            FatigueHazardModel(hazard_by_bucket=dict(artifact_data.FATIGUE_HAZARD_BY_BUCKET))
            if artifact_data.FATIGUE_HAZARD_AVAILABLE
            else None
        )
        return ModelArtifact(
            seed=artifact_data.TRAINING_SEED,
            uplift_available=artifact_data.UPLIFT_AVAILABLE,
            uplift_reason=artifact_data.UPLIFT_UNAVAILABLE_REASON,
            uplift_model=uplift_model,
            fatigue_hazard_available=artifact_data.FATIGUE_HAZARD_AVAILABLE,
            fatigue_hazard_reason=artifact_data.FATIGUE_HAZARD_UNAVAILABLE_REASON,
            fatigue_hazard_model=fatigue_hazard_model,
        )
    except AttributeError as exc:
        raise CommittedArtifactUnavailableError(
            f"{module_name} is missing an expected field: {exc}"
        ) from exc


def build_model_artifact_holdout(seed: int, fraction: float) -> ModelArtifact:
    """Phase 7's entry point (spec §8.9) — a SEPARATE function from
    `build_model_artifact` above, which stays untouched. Calls
    `sampark.models.uplift.train_uplift_model_holdout` and
    `sampark.models.fatigue_hazard.train_fatigue_hazard_model_holdout`,
    both deterministic given `(seed, fraction)`. Packages the result into
    the SAME `ModelArtifact` shape as Phase 6 (so `is_valid_for_scoring()`
    and every downstream consumer needs no new type), with per-component
    availability recorded separately, exactly as Phase 6 already does —
    "uplift worked, hazard didn't" (or vice versa) stays legible rather
    than collapsing into one `available=False` (Phase 7 design lock,
    Decision 6)."""
    from sampark.models.fatigue_hazard import train_fatigue_hazard_model_holdout
    from sampark.models.uplift import train_uplift_model_holdout

    uplift_result = train_uplift_model_holdout(seed, fraction)
    fatigue_result = train_fatigue_hazard_model_holdout(seed, fraction)
    return ModelArtifact(
        seed=seed,
        uplift_available=uplift_result.available,
        uplift_reason=uplift_result.reason,
        uplift_model=uplift_result.model,
        fatigue_hazard_available=fatigue_result.available,
        fatigue_hazard_reason=fatigue_result.reason,
        fatigue_hazard_model=fatigue_result.model,
    )

